from generateCode import *

instances = 32
fname = "mux32to1by32.v"

genWarning = """// WARNING: THIS FILE WAS GENERATED. DO NOT MODIFY\n"""


inputFmt = "input{}"
muxFmt = "assign mux[{0}] = input{0};"

repeatedInput  = repeatNTimes(inputFmt, instances, delim=", ", end="")
repeatedMux = repeatNTimes(muxFmt, instances, delim="\n")

baseStr = """
module mux32to1by32
(
output[31:0]  out,
input[4:0]    address,
input[31:0]   {}
);
wire[31:0] mux[31:0];		// Create a 2D array of wires
{}

assign out = mux[address];	// Connect the output of the array
endmodule

""".format(repeatedInput,repeatedMux)

saveToFile(fname, genWarning + baseStr)